service: footie

plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.shoreditch.football
    staging: staging.shoreditch.football
    dev: dev.shoreditch.football

  customDomain:
    basePath: ''
    certificateName: "*.shoreditch.football"
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    createRoute53Record: true

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  matches_read:
    handler: bin/footie
    environment:
      RESOURCE: matches
      METHOD: read
    events:
      - http:
          path: matches/{id}
          method: get
          private: true
          request:
            parameters:
               paths:
                 id: true
  matches_write:
    handler: bin/footie
    environment:
      RESOURCE: matches
      METHOD: write
    events:
      - http:
          path: matches/{id}
          method: put
          private: true
          request:
            parameters:
               paths:
                 id: true
  matches_create:
    handler: bin/footie
    environment:
      RESOURCE: matches
      METHOD: create
    events:
      - http:
          path: matches
          method: post
          private: true
  matches_delete:
    handler: bin/footie
    environment:
      RESOURCE: matches
      METHOD: delete
    events:
      - http:
          path: matches/{id}
          method: delete
          private: true
          request:
            parameters:
               paths:
                 id: true
  players_read:
    handler: bin/footie
    environment:
      RESOURCE: players
      METHOD: read
    events:
      - http:
          path: players/{id}
          method: get
          private: true
          request:
            parameters:
               paths:
                 id: true
  players_write:
    handler: bin/footie
    environment:
      RESOURCE: players
      METHOD: write
    events:
      - http:
          path: players/{id}
          method: put
          private: true
          request:
            parameters:
               paths:
                 id: true
  players_create:
    handler: bin/footie
    environment:
      RESOURCE: players
      METHOD: create
    events:
      - http:
          path: players
          method: post
          private: true
  players_delete:
    handler: bin/footie
    environment:
      RESOURCE: players
      METHOD: delete
    events:
      - http:
          path: players/{id}
          method: delete
          private: true
          request:
            parameters:
               paths:
                 id: true
  groups_read:
    handler: bin/footie
    environment:
      RESOURCE: groups
      METHOD: read
    events:
      - http:
          path: groups/{id}
          method: get
          private: true
          request:
            parameters:
               paths:
                 id: true
  groups_write:
    handler: bin/footie
    environment:
      RESOURCE: groups
      METHOD: write
    events:
      - http:
          path: groups/{id}
          method: put
          private: true
          request:
            parameters:
               paths:
                 id: true
  groups_create:
    handler: bin/footie
    environment:
      RESOURCE: groups
      METHOD: create
    events:
      - http:
          path: groups
          method: post
          private: true
  groups_delete:
    handler: bin/footie
    environment:
      RESOURCE: groups
      METHOD: delete
    events:
      - http:
          path: groups/{id}
          method: delete
          private: true
          request:
            parameters:
               paths:
                 id: true
  bookings_read:
    handler: bin/footie
    environment:
      RESOURCE: bookings
      METHOD: read
    events:
      - http:
          path: bookings/{id}
          method: get
          private: true
          request:
            parameters:
               paths:
                 id: true
  bookings_write:
    handler: bin/footie
    environment:
      RESOURCE: bookings
      METHOD: write
    events:
      - http:
          path: bookings/{id}
          method: put
          private: true
          request:
            parameters:
               paths:
                 id: true
  bookings_create:
    handler: bin/footie
    environment:
      RESOURCE: bookings
      METHOD: create
    events:
      - http:
          path: bookings
          method: post
          private: true
  bookings_delete:
    handler: bin/footie
    environment:
      RESOURCE: bookings
      METHOD: delete
    events:
      - http:
          path: bookings/{id}
          method: delete
          private: true
          request:
            parameters:
               paths:
                 id: true

resources:
  Resources:
    PlayersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: "players"
        Tags:
          - Key: application
            Value: footie
    MatchesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: "matches"
        Tags:
          - Key: application
            Value: footie
    GroupsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: "player_groups"
        Tags:
          - Key: application
            Value: footie
    BookingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: "group_bookings"
        Tags:
          - Key: application
            Value: footie
    AcksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: "acknowledgements"
        Tags:
          - Key: application
            Value: footie
